### ISSUE TITLE
java.lang.IllegalStateException: Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by farukguler** [BugBattle/Android-SDK#4]
Hi,
We are getting an error for Android 8.0 users when we trigger the bug battle ui. Here is the crash log : 

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ozan.android.debug/bugbattle.io.bugbattle.view.ImageEditor}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2858)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)`

**Comment by boehlerlukas** [comment]
Hey @farukguler !

Thanks for your message. @niklasfessler will check that out in the afternoon and get back to you as soon as possible.

Best regards,
Lukas

**Comment by niklasfessler** [comment]
Hey @farukguler,

i found the bug in our SDK. It happens on Android 8 and earlier, when the background is set to translucent and we try to access the screen orientation. This is fixed now by checking the android version.

The bug is fixed in Version 3.0.20:
com.github.BugBattle:BugBattle-Android-SDK:3.0.20

Thanks for your feedback. I will close the Issue after a positive feedback.

Greetings Niklas

**Comment by farukguler** [comment]
Hey @niklasfessler ,
Thanks for the quick reply, we check the v3.0.20. It is working as expected without crash on Android 8.0 devices.

Kind Regards,
Faruk

**Comment by niklasfessler** [comment]
Bug fixed
